version: 2.0.0-appveyor-{build}
install:
- ps: Invoke-WebRequest 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxWidgets-3.0.2_headers.7z' -OutFile 'headers.7z'
- ps: Invoke-WebRequest 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxMSW-3.0.2_vc100_Dev.7z' -OutFile 'dev.7z'
- ps: Invoke-WebRequest 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxMSW-3.0.2_vc100_ReleaseDLL.7z' -OutFile 'dll.7z'
- ps: Invoke-WebRequest 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxMSW-3.0.2_vc100_ReleasePDB.7z' -OutFile 'pdb.7z'
- ps: 7z x headers.7z -oc:\wxWidgets-3.0.2
- ps: 7z x dev.7z -oc:\wxWidgets-3.0.2
- ps: 7z x dll.7z -oc:\wxWidgets-3.0.2
- ps: 7z x pdb.7z -oc:\wxWidgets-3.0.2
build_script:
- ps: >-
    $env:Path += ";c:\wxWidgets-3.0.2\lib\vc100_dll"

    $env:WXWIN="c:\wxWidgets-3.0.2"

    mkdir cmakebuild

    cd cmakebuild

    cmake .. -G"Visual Studio 10" -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_CXX_FLAGS=/WX

    msbuild TrenchBroom.vcxproj /p:Configuration=Debug /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
 - curl --upload-file TrenchBroom.exe https://transfer.sh/TrenchBroom.exe
